/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.marianetbai.vista;

import es.marianetbai.controlador.UsuarioJpaController;
import es.marianetbai.modelo.Usuario;
import java.util.Locale;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Maria
 */
public class CambioContrasenia extends javax.swing.JPanel {

    private String nuevaContrasenia;
    private String usuarioActual;

    /**
     * Creates new form CambioContraseña
     */
    public CambioContrasenia() {
        Locale.setDefault(Locale.UK);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        lblContraNueva = new javax.swing.JLabel();
        txtUsuarioABuscar = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lblConfirmaContras = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtConfirmarCon = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        lblCabecera = new javax.swing.JLabel();
        lblFondoLogin = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        lblIcono2 = new javax.swing.JLabel();
        lblIcono1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1040, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(250, 244, 251));
        pnlLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setBackground(new java.awt.Color(153, 153, 255));
        btnAceptar.setForeground(new java.awt.Color(51, 51, 51));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/marianetbai/vista/Bundle"); // NOI18N
        btnAceptar.setText(bundle.getString("CambioContrasenia.btnAceptar.text")); // NOI18N
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlLogin.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 110, 40));

        lblContraNueva.setForeground(new java.awt.Color(73, 80, 87));
        lblContraNueva.setText(bundle.getString("CambioContrasenia.lblContraNueva.text")); // NOI18N
        pnlLogin.add(lblContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtUsuarioABuscar.setToolTipText(bundle.getString("CambioContrasenia.txtUsuarioABuscar.toolTipText")); // NOI18N
        txtUsuarioABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioABuscarActionPerformed(evt);
            }
        });
        pnlLogin.add(txtUsuarioABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(153, 153, 255));
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText(bundle.getString("CambioContrasenia.btnCancelar.text")); // NOI18N
        btnCancelar.setToolTipText(bundle.getString("CambioContrasenia.btnCancelar.toolTipText")); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlLogin.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 110, 40));

        lblConfirmaContras.setForeground(new java.awt.Color(73, 80, 87));
        lblConfirmaContras.setText(bundle.getString("CambioContrasenia.lblConfirmaContras.text")); // NOI18N
        pnlLogin.add(lblConfirmaContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblUsuario.setForeground(new java.awt.Color(73, 80, 87));
        lblUsuario.setText(bundle.getString("CambioContrasenia.lblUsuario.text")); // NOI18N
        pnlLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 40));
        pnlLogin.add(txtConfirmarCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cc.png"))); // NOI18N
        pnlLogin.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 70));

        lblCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambioCon.jpg"))); // NOI18N
        pnlLogin.add(lblCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 110));

        lblFondoLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.add(lblFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, 380));

        add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1040, 570));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ellipse 209.png"))); // NOI18N
        pnlFondo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 690, 390));

        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Union.png"))); // NOI18N
        lblIcono1.setText(bundle.getString("CambioContrasenia.lblIcono1.text")); // NOI18N
        lblIcono1.setMaximumSize(new java.awt.Dimension(1040, 570));
        lblIcono1.setMinimumSize(new java.awt.Dimension(1040, 570));
        lblIcono1.setPreferredSize(new java.awt.Dimension(1040, 570));
        pnlFondo.add(lblIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -740, 4590, 1900));

        add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioABuscarActionPerformed
        
    }//GEN-LAST:event_txtUsuarioABuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //cerramos la ventana actual (CambioContrasenia)
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();

        //abrimos la ventana del Login
        JFrame loginFrame = new JFrame("Log in");
        loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        loginFrame.getContentPane().add(new Login());
        loginFrame.pack();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //obtenemos el usuario del campo de texto
        usuarioActual = txtUsuarioABuscar.getText();

        //obtenemos la nueva contraseña y la confirmación del campo de texto
        nuevaContrasenia = txtConfirmarCon.getText();

        //verificamos que se haya proporcionado un usuario y una nueva contraseña
        if (!usuarioActual.isEmpty() && !nuevaContrasenia.isEmpty()) {
            //actualizamos la contraseña en la base de datos
            actualizarContraseñaEnBD(usuarioActual, nuevaContrasenia);
            mostrarMensaje("Password updated successfully");

            //cierro la ventana actual (CambioContrasenia)
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            frame.dispose();

            //y abro la ventana del Login
            JFrame loginFrame = new JFrame("Log in");
            loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            loginFrame.getContentPane().add(new Login());
            loginFrame.pack();
            loginFrame.setVisible(true);
            loginFrame.setLocationRelativeTo(null);
        } else {
            mostrarMensaje("Please complete all the fields");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void actualizarContraseñaEnBD(String usuario, String nuevaContrasenia) {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        UsuarioJpaController ujpa = new UsuarioJpaController(emf);

        try {
            //busco el usuario en la base de datos
            Usuario usuarioBD = ujpa.findUsuarioByUsuario(usuario);

            if (usuarioBD != null) {
                //actualizo la contraseña
                usuarioBD.setPassword(nuevaContrasenia);

                //uso edit para los cambios en la base de datos
                ujpa.edit(usuarioBD);
            } else {
                mostrarMensaje("User not found");
            }
        } catch (Exception ex) {
            mostrarMensaje("Error updating the password: " + ex.getMessage());
        } finally {
            emf.close();
        }
    }
    
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private UsuarioJpaController ujpa;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JLabel lblConfirmaContras;
    private javax.swing.JLabel lblContraNueva;
    private javax.swing.JLabel lblFondoLogin;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtConfirmarCon;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioABuscar;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
