/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.marianetbai.vista;

import es.marianetbai.controlador.UsuarioJpaController;
import es.marianetbai.modelo.Usuario;
import java.awt.event.KeyEvent;
import java.util.Locale;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Maria
 */
public class Login extends javax.swing.JPanel {

    private CambioContrasenia ventanaCambioContrasenia;

    public Login() {
        Locale.setDefault(Locale.UK);
        initComponents();
        ventanaCambioContrasenia = new CambioContrasenia();  
        
        //para si pulsamos enter
        txtContrasenia.setToolTipText("Enter your password");
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyPressed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cbxRecordarUsuario = new javax.swing.JCheckBox();
        btnRegistroUsuario = new javax.swing.JButton();
        lblContrasenia = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JTextField();
        lblCandado = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblCabecera = new javax.swing.JLabel();
        btnOlvidoContrasenia = new javax.swing.JButton();
        lblFondoLogin = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();
        lblIcono2 = new javax.swing.JLabel();
        lblIcono1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1040, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(250, 244, 251));
        pnlLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setForeground(new java.awt.Color(73, 80, 87));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/marianetbai/vista/Bundle"); // NOI18N
        lblUsuario.setText(bundle.getString("Login.lblUsuario.text")); // NOI18N
        pnlLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 40));

        cbxRecordarUsuario.setForeground(new java.awt.Color(73, 80, 87));
        cbxRecordarUsuario.setText(bundle.getString("Login.cbxRecordarUsuario.text")); // NOI18N
        cbxRecordarUsuario.setBorder(null);
        cbxRecordarUsuario.setContentAreaFilled(false);
        cbxRecordarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecordarUsuarioActionPerformed(evt);
            }
        });
        pnlLogin.add(cbxRecordarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btnRegistroUsuario.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistroUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistroUsuario.setText(bundle.getString("Login.btnRegistroUsuario.text")); // NOI18N
        btnRegistroUsuario.setToolTipText(bundle.getString("Login.btnRegistroUsuario.toolTipText")); // NOI18N
        btnRegistroUsuario.setBorder(null);
        btnRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuarioActionPerformed(evt);
            }
        });
        pnlLogin.add(btnRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 210, 40));

        lblContrasenia.setForeground(new java.awt.Color(73, 80, 87));
        lblContrasenia.setText(bundle.getString("Login.lblContrasenia.text")); // NOI18N
        pnlLogin.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(153, 153, 255));
        btnIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnIniciarSesion.setText(bundle.getString("Login.btnIniciarSesion.text")); // NOI18N
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        btnIniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnIniciarSesionKeyPressed(evt);
            }
        });
        pnlLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 40));
        pnlLogin.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 40));

        lblCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lock.png"))); // NOI18N
        pnlLogin.add(lblCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 30, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cc.png"))); // NOI18N
        pnlLogin.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 70));

        lblCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabecera.jpg"))); // NOI18N
        pnlLogin.add(lblCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 110));

        btnOlvidoContrasenia.setForeground(new java.awt.Color(0, 102, 255));
        btnOlvidoContrasenia.setText(bundle.getString("Login.btnOlvidoContrasenia.text")); // NOI18N
        btnOlvidoContrasenia.setToolTipText(bundle.getString("Login.btnOlvidoContrasenia.toolTipText")); // NOI18N
        btnOlvidoContrasenia.setBorder(null);
        btnOlvidoContrasenia.setBorderPainted(false);
        btnOlvidoContrasenia.setContentAreaFilled(false);
        btnOlvidoContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidoContraseniaActionPerformed(evt);
            }
        });
        pnlLogin.add(btnOlvidoContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 250, 20));

        lblFondoLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.add(lblFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, 380));

        add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1040, 570));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ellipse 209.png"))); // NOI18N
        pnlFondo.add(lblIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 690, 390));

        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Union.png"))); // NOI18N
        lblIcono1.setText(bundle.getString("Login.lblIcono1.text")); // NOI18N
        lblIcono1.setMaximumSize(new java.awt.Dimension(1040, 570));
        lblIcono1.setMinimumSize(new java.awt.Dimension(1040, 570));
        lblIcono1.setPreferredSize(new java.awt.Dimension(1040, 570));
        pnlFondo.add(lblIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -740, 4590, 1900));

        add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuarioActionPerformed
        //abrimos la ventana para el cambio de contraseña
        JFrame frame = new JFrame("New user");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(new RegistroUsuario());
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        ujpa = new UsuarioJpaController(emf);
    }//GEN-LAST:event_btnRegistroUsuarioActionPerformed

    private void btnOlvidoContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidoContraseniaActionPerformed
        //abrimos la ventana para el cambio de contraseña
        JFrame frame = new JFrame("New password");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(new CambioContrasenia());
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        ujpa = new UsuarioJpaController(emf);
    }//GEN-LAST:event_btnOlvidoContraseniaActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        ujpa = new UsuarioJpaController(emf);

        String usuario = txtUsuario.getText();
        String pass = txtContrasenia.getText();

        //criteriaBuilder para la consulta
        CriteriaBuilder cb = emf.getCriteriaBuilder();
        CriteriaQuery<Usuario> cq = cb.createQuery(Usuario.class);
        Root<Usuario> root = cq.from(Usuario.class);

        cq.select(root)
          .where(cb.equal(root.get("usuario"), usuario));
        TypedQuery<Usuario> query = emf.createEntityManager().createQuery(cq);
        
        try {
            Usuario usuarioBD = query.getSingleResult();
            //comprobamos la contraseña
            if (usuarioBD.getPassword().equals(pass)) {
                mostrarMensaje("Correct login");
                //cerramos la ventana actual (Login)
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.dispose();
                //y abrimos la ventana del menú (MenuFacturas)
                MenuFacturas menuFacturas = new MenuFacturas();
                menuFacturas.setVisible(true);
            } else {
                //si la contraseña es incorrecta
                mostrarMensaje("Incorrect password. Click 'Forgot your password?' to restore it.");
            }
        } catch (NoResultException ex) {
            //si el usuario no ha sido encontrado
            mostrarMensaje("User not found");
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnIniciarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarSesionKeyPressed

    }//GEN-LAST:event_btnIniciarSesionKeyPressed

    private void cbxRecordarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecordarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRecordarUsuarioActionPerformed

    //para cuando pulsamos enter si no quiero presionar "Iniciar sesión"
    private void txtContraseniaKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnIniciarSesionActionPerformed(null);
        }
    }
    
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    
    private UsuarioJpaController ujpa;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnOlvidoContrasenia;
    private javax.swing.JButton btnRegistroUsuario;
    private javax.swing.JCheckBox cbxRecordarUsuario;
    private javax.swing.JLabel lblCabecera;
    private javax.swing.JLabel lblCandado;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblFondoLogin;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
