/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.marianetbai.vista;
import es.marianetbai.modelo.Factura;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Maria
 */
public class MenuFacturas extends javax.swing.JFrame {
    /**
     * Creates new form MenuFacturas
     */
    ImagenFondo ejemplo = new ImagenFondo();
    
    //lista temporal para usar el deshacer
    private Factura ultimaFacturaEliminada;
    
    public MenuFacturas() {
        Locale.setDefault(Locale.UK);
        this.setContentPane(ejemplo);
        this.setSize(1040,570);
        this.setLocationRelativeTo(null);
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcciones = new javax.swing.JMenu();
        menuAddFactura = new javax.swing.JMenuItem();
        menuEditarFactura = new javax.swing.JMenuItem();
        MenuEliminarFactura = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuDeshacer = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuInfoAlumno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/marianetbai/vista/Bundle"); // NOI18N
        setTitle(bundle.getString("MenuFacturas.title")); // NOI18N
        setSize(new java.awt.Dimension(1040, 570));

        menuAcciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-clickstream-48.png"))); // NOI18N
        menuAcciones.setText(bundle.getString("MenuFacturas.menuAcciones.text")); // NOI18N
        menuAcciones.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        menuAddFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAddFactura.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        menuAddFactura.setForeground(new java.awt.Color(102, 102, 102));
        menuAddFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-añadir-48.png"))); // NOI18N
        menuAddFactura.setText(bundle.getString("MenuFacturas.menuAddFactura.text")); // NOI18N
        menuAddFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddFacturaActionPerformed(evt);
            }
        });
        menuAcciones.add(menuAddFactura);

        menuEditarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuEditarFactura.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        menuEditarFactura.setForeground(new java.awt.Color(102, 102, 102));
        menuEditarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-48 (1).png"))); // NOI18N
        menuEditarFactura.setText(bundle.getString("MenuFacturas.menuEditarFactura.text")); // NOI18N
        menuEditarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarFacturaActionPerformed(evt);
            }
        });
        menuAcciones.add(menuEditarFactura);

        MenuEliminarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuEliminarFactura.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        MenuEliminarFactura.setForeground(new java.awt.Color(102, 102, 102));
        MenuEliminarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-48.png"))); // NOI18N
        MenuEliminarFactura.setText(bundle.getString("MenuFacturas.MenuEliminarFactura.text")); // NOI18N
        MenuEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEliminarFacturaActionPerformed(evt);
            }
        });
        menuAcciones.add(MenuEliminarFactura);

        jMenuBar1.add(menuAcciones);

        menuEdicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-48.png"))); // NOI18N
        menuEdicion.setText(bundle.getString("MenuFacturas.menuEdicion.text")); // NOI18N
        menuEdicion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        menuDeshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDeshacer.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        menuDeshacer.setForeground(new java.awt.Color(102, 102, 102));
        menuDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-deshacer-48 (1).png"))); // NOI18N
        menuDeshacer.setText(bundle.getString("MenuFacturas.menuDeshacer.text")); // NOI18N
        menuDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeshacerActionPerformed(evt);
            }
        });
        menuEdicion.add(menuDeshacer);

        jMenuBar1.add(menuEdicion);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-ayuda-48.png"))); // NOI18N
        menuAyuda.setText(bundle.getString("MenuFacturas.menuAyuda.text")); // NOI18N
        menuAyuda.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });

        menuInfoAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuInfoAlumno.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        menuInfoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        menuInfoAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-alumna-48.png"))); // NOI18N
        menuInfoAlumno.setText(bundle.getString("MenuFacturas.menuInfoAlumno.text")); // NOI18N
        menuInfoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoAlumnoActionPerformed(evt);
            }
        });
        menuAyuda.add(menuInfoAlumno);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarFacturaActionPerformed
        EditarFactura editarFactura = new EditarFactura();
        editarFactura.setVisible(true);
    }//GEN-LAST:event_menuEditarFacturaActionPerformed

    private void menuAddFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddFacturaActionPerformed
        AddFactura addFactura = new AddFactura();
        addFactura.setVisible(true);
    }//GEN-LAST:event_menuAddFacturaActionPerformed

    private void MenuEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEliminarFacturaActionPerformed
        EliminarFactura eliminarFactura = new EliminarFactura();
        eliminarFactura.setVisible(true);
    }//GEN-LAST:event_MenuEliminarFacturaActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
         
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuInfoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoAlumnoActionPerformed
        PantallaAyuda pantallaAyuda = new PantallaAyuda();
        pantallaAyuda.setVisible(true);
    }//GEN-LAST:event_menuInfoAlumnoActionPerformed

    private void menuDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeshacerActionPerformed
        DeshacerFactura pantallaDeshacer = new DeshacerFactura();
        pantallaDeshacer.setVisible(true);
    }//GEN-LAST:event_menuDeshacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEliminarFactura;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAcciones;
    private javax.swing.JMenuItem menuAddFactura;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuDeshacer;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuEditarFactura;
    private javax.swing.JMenuItem menuInfoAlumno;
    // End of variables declaration//GEN-END:variables


    class ImagenFondo extends JPanel{
        private Image imagen;
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
